[package]
name = "goose-test"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[[bin]]
name = "capture"
path = "src/bin/capture.rs"

[dependencies]
clap = { workspace = true }
goose-test-support = { version = "1.51.0", path = "../goose-test-support" }
rmcp = { workspace = true, features = ["transport-io"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
